### ISSUE TITLE
Template HTML CSS

### ISSUE THREAD

**Issue by eduardosgalmeida** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t3-consumoconsciente#24]

**Comment by SofiaPittaSesso** [comment]
- [ ] Cabeçalho @VitorLinas 
- [ ] Cards com dicas @eduardosgalmeida 
- [ ] Quem somos @Carminha2023 
- [ ] Footer @Reis008 
- [ ] Responsividade @SofiaPittaSesso
