### ISSUE TITLE
Pesquisar o estado da arte - outras aplicações que existem com o mesmo propósito

### ISSUE THREAD

**Issue by SofiaPittaSesso** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t3-consumoconsciente#39]

**Comment by Carminha2023** [comment]
Introdução

O Consumismo é o ato que está relacionado ao consumo excessivo, ou seja, à compra de produtos ou serviços de modo exagerado.
O consumismo é característico das sociedades modernas capitalistas e da expansão da globalização.
Ele está inserido na denominada: “Sociedade do Consumo”, onde ocorre o consumo massivo e desenfreado de bens e serviços que visa, sobretudo, o lucro das empresas e o desenvolvimento econômico.
Essa postura consumista surgiu a partir da Revolução Industrial no século XVIII, de forma que os processos industriais possibilitaram o aumento da produção e, consequentemente, do consumo de produtos.
Causa o consumismo
O consumismo não tem uma causa específica. Esse comportamento é motivado por uma série de fatores que envolvem desde a [mídia](https://www.politize.com.br/acessibilidade-nas-midias-sociais-entrevista-sidney-andrade/) até as táticas de propaganda utilizadas por [organizações empresariais](https://www.politize.com.br/relacao-entre-empresas-e-politicos/).
Quais são os impactos do consumismo
Também é possível que o consumismo evolua, em algumas pessoas, para um quadro clínico, como a síndrome de Diógenes. Nessa situação o indivíduo, tem tal apego pelos bens materiais adquiridos que não consegue parar de comprar nem se desfazer de produtos antigos.

Objetivo Geral
Desenvolver uma aplicação que atenda aos usuários que precisam mudar hábitos de gastar sem necessidade.
Objetivos específicos
1. Planeje suas compras
2. Conheça a empresa de quem está comprando
3. Não compre produtos falsificados
4. Valorize as iniciativas de responsabilidade social das marcas
5. Fique atento a geração de lixo
6. Comece a fazer listas
7. Pense e repense

Justificativa
A pessoa com comportamento consumista costuma ter muitos problemas financeiros. Em determinado momento ela começa a gastar mais do que ganha e transforma a vida financeira em um caos. Nesse caso, é impossível economizar, guardar dinheiro e alcançar objetivos que não sejam comprar.
10 sinais de que o consumo exagerado está levando a sua felicidade embora

- Não dorme bem
- Alimenta-se mal
- Uso indevido cheque especial/ cartões de crédito
- Embaralha as contas
- Mudanças de humor ou melancolia
- Esconde as compras dos familiares
- Descuida do relacionamento
- Negar a verdade
- Fica sem noção
- Perde objetos conquistados
Atenção!

Ao chegar nessa situação e caso não haja solução, procure um profissional para ajudar a solucionar o problema o quanto antes. 

Público-Alvo
O público alvo da aplicação provém de usuários de todos os gêneros e idade maior 18 anos e principalmente se ele for destinado à Geração Z.
